name: Deploy
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Python Syntax Checker
        uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
      - shell: bash
        env:
          TOKEN: ${{ secrets.TOKEN }}
          DEPLOY_UID: ${{ secrets.DEPLOY_UID }}
        run: |
            curl http://app.snehit.dev/redeploy/$DEPLOY_UID/$TOKEN/flyingcakes85/easywriter
